### ISSUE TITLE
The _t type suffix is reserved by Posix

### ISSUE THREAD

**Issue by kirbyfan64** [wolkykim/qlibc#22]
Someone pointed it out in the Reddit thread; see [here](http://stackoverflow.com/a/3225396/2097780) for more info. Basically, it's very bad.

It really sucks. I've been doing this for a while and had no idea...

**Comment by wolkykim** [comment]
The reason I put _t for the object is to help users to identify and treat the returned data as an object. It's like saying that accessing the object's internal directly is not intended by the implementation.

POSIX standard reserves _t to prevent possible name conflicts with user codes. I was considering altenatives like _o, _obj, _x, _q or no sufixes but I ended up using qXXX_t notation thinking that using _t sufix would deliver the intended meaning clearly to people's common sense.

Someone will agree with me and someone will not. And as you know qLibc has more of those that are not in everyone's preference such as using bool type, C99 style, OO pointer concepts. But after all, as you mentioned there, qLibc is written to be practical I guess.

**Comment by wolkykim** [comment]
BTW, what do you think?

**Comment by kirbyfan64** [comment]
I don't really care whichever way. I personally prefer CamelCase for type names, but that's just my personal style.

**Comment by nurupo** [comment]
>It's like saying that accessing the object's internal directly is not intended by the implementation.

You could make the objects be [opaque pointers](http://en.wikipedia.org/wiki/Opaque_pointer) -- just a declaration in the public header and definition in the .c file, i.e. the library user would have no idea what a struct contains and wouldn't be able to mess with its internals.

Opaque pointer idiom is used by libraries extensivly, because besides providing the useful information hiding, it helps with making a library be binary-code-compatible between different versions. For example, if you were to add a few new variables to the hash table struct, applications using the library version without that change would link against the library binary with that change without need to be recompiled against the newer version of the library. If you don't support binary-code-compatibility, the application wouldn't be able to link against the new library version and would have be recompiled against it. This is quite important on Linux systems, since they use shared libraries extensivly and it's undesired to have to update all the applications using library X just because the library X got updated.

**Comment by wolkykim** [comment]
@nurupo That's good to know. I think we should consider that adapting opaque pointers for better encapsulization. Is there any possible drawbacks or compatibility issues?

**Comment by nurupo** [comment]
Not that I know of. Also, note that using opaque pointers doesn't automatically grant you binary compatibility, it just helps with it greatly, but you can still find ways to break the binary compatibility.

Here are some links with some tips on binary compatibility: [1](http://stackoverflow.com/questions/7217258/), [2](https://techbase.kde.org/Policies/Binary_Compatibility_Issues_With_C++), [3](https://www.youtube.com/watch?v=PHrXGHDd9no) [slides](https://events.linuxfoundation.org/sites/events/files/slides/Binary_Compatibility_for_library_devs.pdf) (he is thiago on #qt at freenode IRC, if you have any questions).

**Comment by wolkykim** [comment]
That's sweet!

**Comment by wolkykim** [comment]
Seems this is not something we want to address at this point. I'm closing the issue now. Please feel free to reopen the issue when needed.
