### ISSUE TITLE
qvector_t should use an array as its data container

### ISSUE THREAD

**Issue by burtonageo** [wolkykim/qlibc#24]
The expected behaviour of a vector is:
a) O(1) random element access and append.
b) O(n) iteration, element removal, and element insertion
c) Specify capacity
b) sequential layout in memory.

If qlibc is targeting C99, then it could use a flexible array member to keep the vector size info together with
the array.

**Comment by wolkykim** [comment]
qvector() is implemented witth linked-list data structure to make it flexible and to eliminate the need of c) specify capacity. It's easier for users to use because it doesn't need to know what size and how big the objects will be. But it loses O(1) random element access but O(n). But it is still O(1) for append and same O(n) for iteration.

In my practice, random access to vector is kind of infrequent and use vector like Obstacks(from GNU). So I choose to use linked-list for the implementation. If we need a vector with O(1) random access, we can make one for it? I just didn't feel the need so far.

**Comment by wolkykim** [comment]
Closing now, feel free to reopen.
