### ISSUE TITLE
qhashtbl(0, QHASHTBL_THREADSAFE): double free or corruption (top): 0x0000000001d100b0 ***

### ISSUE THREAD

**Issue by allanwind** [wolkykim/qlibc#46]
I modified examples/hashtbl.c as follows:

-     qhashtbl_t *tbl = qhashtbl(0, 0);
+    qhashtbl_t *tbl = qhashtbl(0, QHASHTBL_THREADSAFE);

which then crashes with:

allan@vent:~/src/qlibc/examples$ ./hashtbl 
*** Error in `./hashtbl': double free or corruption (top): 0x00000000015010b0 ***
Aborted

What am I missing?

**Comment by kirbyfan64** [comment]
For some reason, [this](https://github.com/wolkykim/qlibc/blob/master/src/containers/qhashtbl.c#L144) is returning true. Likely an issue with the mutex allocation code, because I can reproduce this, and I have *plenty* of memory left.

Now, when it jumps to `malloc_failure`, it calls `qhashtbl_free`. According to GDB, this is where the corruption occurs.

**Comment by kirbyfan64** [comment]
Found it!

[This line](https://github.com/wolkykim/qlibc/blob/master/src/containers/qhashtbl.c#L179) frees `tbl->slots`, BUT it doesn't set it to `NULL`. Two lines later, `qhashtbl_free` is called, which [frees it again](https://github.com/wolkykim/qlibc/blob/master/src/containers/qhashtbl.c#L712).

This still doesn't explain why the `malloc` failure is even occurring, though...
